

function [spike_train,hd,positions] = load_spike(time_f_t, spike, dlc_m,unit_id,session_num)

if length(session_num)==1
    [spike_train,hd,positions] = load_spike_single_session(time_f_t, ...
        spike, ...
        dlc_m, ...
        unit_id);
else
    [spike_train,hd,positions] = load_spike_multi_session(time_f_t, ...
        spike, ...
        dlc_m, ...
        unit_id, ...
        session_num);
end

end
