function [id] = filter_place_cell(merge_spk,UI_as)
%FILTER_PLACE_CELL Summary of this function goes here
%   Detailed explanation goes here
% [spikes] = spi_classify(merge_spk,positions)

id = find(merge_spk.presence_ratio>0.9& ...
    merge_spk.isi_violations_ratio<0.2& ...
    merge_spk.amplitude_median>40& ...
    string(merge_spk.UIanimal_session)==UI_as& ...
    merge_spk.firing_range>0.1& ...
    merge_spk.firing_range<=10& ...
    merge_spk.peak_to_valley>0.000475& ...
    merge_spk.reject_h0==1);
end
