
function  plot_screening(positions,hd,spike_train,unit_id,options)

arguments
    positions {mustBeNonmissing}
    hd {mustBeNonmissing}
    spike_train {mustBeNonmissing}
    unit_id {mustBeNonmissing}
    options.binWidth (1,1)  {mustBeNumeric} = 1/28
    options.hdBinWidth (1,1)  {mustBeNumeric} = 10
    options.smooth (1,1)  {mustBeNumeric} = 0
    options.save_plot (1,1)  string = 'True'
    options.save_path (1,1)  string = 'Q:\sachuriga\Record_archive\Record_examples'
    options.animalID (1,1)  string = '65165'
    options.day_num (1,1)  string = '2023-07-01'
    options.session (1,1)  string = 'A'
end

if isstruct(positions)==1
    [size_colum,size_raw] = plot_size(unit_id);
    plot_screening_MultiSession(positions, ...
        hd, ...
        spike_train, ...
        "PlotSize",[size_colum size_raw], ...
        'binWidth',options.binWidth,...
        'hdBinWidth', options.hdBinWidth, ...
        'smooth',options.smooth, ...
        'save_plot',options.save_plot,...
        'save_path',options.save_path,...
        'animalID',options.animalID,...
        'day_num',options.day_num)

else

    [size_colum,size_raw] = plot_size(unit_id);
    plot_screening_SingleSession(positions, ...
        hd, ...
        spike_train, ...
        "PlotSize",[size_colum size_raw], ...
        'binWidth',options.binWidth,...
        'hdBinWidth', options.hdBinWidth, ...
        'smooth',options.smooth, ...
        'save_plot',options.save_plot,...
        'save_path',options.save_path,...
        'animalID',options.animalID,...
        'day_num',options.day_num, ...
        'session',options.session)
end

end
