clear all
close all

animalID='65091';
day_num = '2023-08-08';
session_num = 'B';
folder_recording = 'Q:\sachuriga\OpenEphys';
video_folder = 'Q:\sachuriga\OpenEphys_video';
save_plot='True';
save_path='Q:\sachuriga\Record_archive\Record_examples';

%% Load data
% Load unit id
[unit_id] = load_unitid(animalID,day_num,folder_recording,session_num);
[ch_id] = load_best_ch(animalID,day_num,folder_recording,session_num);

% Load LFP
[continuous] = load_LFP(animalID,day_num,folder_recording,session_num);

% Load spike and dlc tracking data
[time_f_t, spike, dlc_m] = load_data(animalID, ...
    day_num, ...
    session_num, ...
    folder_recording, ...
    video_folder);

% Load spike train
[spike_train,hd,positions] = load_spike(time_f_t, ...
    spike, ...
    dlc_m, ...
    unit_id, ...
    session_num);

% Calculate plot size
[size_colum,size_raw] = plot_size(unit_id);

% %% plot
% % Screening place cells
% plot_screening(positions, ...
%     hd, ...
%     spike_train, ...
%     unit_id, ...
%     'binWidth',1/25,...
%     'hdBinWidth', 12, ...
%     'smooth',2, ...
%     'save_plot',save_plot,...
%     'save_path',save_path,...
%     'animalID',animalID,...
%     'day_num',day_num, ...
%     'session',session_num)

% % plot single unit's activity
% plot_single_cell(positions, ...
%     hd, ...
%     spike_train, ...
%     unit_id, ...
%     ch_id, ...
%     continuous, ...
%     'Nbins',1/20,...
%     'hdBinWidth', 1, ...
%     'smooth',1, ...
%     'save_plot',save_plot,...
%     'save_path',save_path,...
%     'animalID',animalID,...
%     'day_num',day_num, ...
%     'session',session_num)

Load_place_cell(positions, ...
    hd, ...
    spike_train, ...
    unit_id, ...
    ch_id, ...
    continuous, ...
    'Nbins',1/20,...
    'hdBinWidth', 1, ...
    'smooth',1, ...
    'save_plot',save_plot,...
    'save_path',save_path,...
    'animalID',animalID,...
    'day_num',day_num, ...
    'session',session_num)

cd Q:\sachuriga\Sachuriga_Matlab\Sorting_analyze

